version: "3.7"

services:
  meetup_scheduling:
    container_name: meetup_scheduling
    build:
      dockerfile: Meetup.Scheduling/Dockerfile
      context: ./scheduling
    image: meetup-scheduling
    restart: always
    ports:
      - 5000:80
    environment:
      ConnectionStrings__MeetupScheduling: "Host=postgres;Database=meetup;Username=meetup;Password=password;SearchPath=group_management"
      RabbitMQ__Host: rabbitmq
      SEQ_URL: http://seq:5341
      JAEGER_HOST: jaeger
      ASPNETCORE_ENVIRONMENT: Development

  meetup_scheduling_queries:
    container_name: meetup_scheduling_queries
    build:
      dockerfile: Meetup.Scheduling.Queries/Dockerfile
      context: ./scheduling
    image: meetup-scheduling-queries
    restart: always
    ports:
      - 8000:80
    environment:
      ConnectionStrings__MeetupScheduling: "Host=postgres;Database=meetup;Username=meetup;Password=password;SearchPath=group_management"
      SEQ_URL: http://seq:5341
      JAEGER_HOST: jaeger

  meetup_scheduling_process_manager:
    container_name: meetup_scheduling_process_manager
    build:
      dockerfile: Meetup.Scheduling.ProcessManager/Dockerfile
      context: ./scheduling
    image: meetup-scheduling-process-manager
    restart: always
    environment:
      RabbitMQ__Host: rabbitmq
      SEQ_URL: http://seq:5341
      JAEGER_HOST: jaeger

  meetup_scheduling_integration_events_publisher:
    container_name: meetup_scheduling_integration_events_publisher
    build:
      dockerfile: Meetup.Scheduling.IntegrationEventsPublisher/Dockerfile
      context: ./scheduling
    image: meetup-scheduling-integration-events-publisher
    restart: always
    environment:
      RabbitMQ__Host: rabbitmq
      SEQ_URL: http://seq:5341
      JAEGER_HOST: jaeger

  meetup_scheduling_async_projector:
    container_name: meetup_scheduling_async_projector
    build:
      dockerfile: Meetup.Scheduling.AsyncProjector/Dockerfile
      context: ./scheduling
    image: meetup-scheduling-async-projector
    restart: always
    environment:
      ConnectionStrings__MeetupScheduling: "Host=postgres;Database=meetup;Username=meetup;Password=password;SearchPath=group_management"
      SEQ_URL: http://seq:5341


networks:
  default:
    name: meetup-network