version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
#    command:
#      - --replSet 
#      - rs0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
  # enable replicase set for change log
  # mongo -u root -p mysecretpassword
  # rs.initiate();

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq-plugins
    ports:
      - "15672:15672"
      - "5672:5672"
