version: "3.7"

services:
  meetup-events:
    image: paulopez/meetup-events
    container_name: meetup-events
    build:
      context: ./MeetupEvents
    ports:
      - 5000:5000
    environment:
      ConnectionStrings__MeetupEvents: "Host=postgres;Port=5432;Database=meetup_events;Username=postgres;Password=mysecretpassword;"
    restart: always
  
networks:
  default:
    name: meetup-network
