version: "3.7"

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword

#  pgadmin4:
#    image: dpage/pgadmin4
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: paulopez78@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: mysecretpassword